/**
 * AUDIT REASON → Türkçe kullanıcı mesajları (PART 17)
 * --------------------------------------------------------------
 * Developer code'u kullanıcıya tek başına gösterilmez.
 * --------------------------------------------------------------
 */
import { AUDIT_REASON_CODES as C, AUDIT_WARNING_CODES as W } from './programAuditConstants';

export const AUDIT_REASON_LABELS = Object.freeze({
  [C.AUDIT_PROGRAM_NOT_FOUND]: 'Program kaydı bulunamadı.',
  [C.AUDIT_VERSION_NOT_FOUND]: 'Program sürümü bulunamadı.',
  [C.AUDIT_VERSION_RELATION_MISMATCH]: 'Program ile sürüm ilişkisi tutarsız.',
  [C.AUDIT_INVALID_SETTINGS_SNAPSHOT]: 'Program ayarları eksik veya geçersiz.',
  [C.AUDIT_ENGINE_VERSION_INCOMPATIBLE]: 'Program, farklı bir motor sürümüyle üretilmiş.',
  [C.AUDIT_INPUT_FINGERPRINT_MISMATCH]: 'Program parmak izi, kayıtlı içerikle eşleşmiyor.',
  [C.AUDIT_DAY_COUNT_MISMATCH]: 'Planlanan antrenman gün sayısı tutarsız.',
  [C.AUDIT_ORDINAL_INVALID]: 'Antrenman sıra numaraları hatalı (boşluk veya tekrar var).',
  [C.AUDIT_DATE_ORDER_INVALID]: 'Antrenman tarihleri sıralı değil veya tekrarlı.',
  [C.AUDIT_DATE_OUT_OF_RANGE]: 'Bir antrenman tarihi program tarih aralığı dışında.',
  [C.AUDIT_WEEKDAY_INVALID]: 'Bir antrenman, seçilen günlerden birinde değil.',
  [C.AUDIT_CALENDAR_DURATION_MISMATCH]: 'Program bitiş tarihi süreye uymuyor.',
  [C.AUDIT_SESSION_DURATION_MISMATCH]: 'Günlük süre, seçilen süreyle eşleşmiyor.',
  [C.AUDIT_BUDGET_SNAPSHOT_MISMATCH]: 'Zaman bütçesi, yeniden hesaplananla eşleşmiyor.',
  [C.AUDIT_DAY_TIME_MISMATCH]: 'Bu antrenmanın toplam planlı süresi seçilen günlük süreyle eşleşmiyor.',
  [C.AUDIT_BLOCK_ORDER_INVALID]: 'Blokların sıralamasında boşluk veya tekrar var.',
  [C.AUDIT_ROLE_COMPOSITION_INVALID]: 'Gün türüyle blok yapısı uyuşmuyor.',
  [C.AUDIT_PROGRESSION_MISMATCH]: 'İlerleme (faz) bilgisi tutarsız.',
  [C.AUDIT_WEEKLY_ROLE_MISMATCH]: 'Haftalık antrenman dağılımı tutarsız.',
  [C.AUDIT_BALANCED_CAP_MISMATCH]: 'Dengeli sınır değerleri tutarsız.',
  [C.AUDIT_MULTIPLE_PROGRESSION_PUSH]: 'Tek seansta birden fazla ilerleme boyutu zorlanmış.',
  [C.AUDIT_UNKNOWN_BOXING_COMBINATION]: 'Bilinmeyen boks kombinasyonu kullanılmış.',
  [C.AUDIT_BOXING_MOVE_ORDER_MISMATCH]: 'Kombinasyon hareket sırası değiştirilmiş.',
  [C.AUDIT_SLIP_IN_ATTACK]: 'Saldırı blokunda Slip hareketi var.',
  [C.AUDIT_BOXING_COMBO_CAP_EXCEEDED]: 'Kombinasyon, izin verilen hamle sayısını aşıyor.',
  [C.AUDIT_BOXING_TRANSITION_INVALID]: 'Hareketler arası geçiş onaylı listede değil.',
  [C.AUDIT_BOXING_CONTEXT_INVALID]: 'Kombinasyon için gereken bağlam sağlanmamış.',
  [C.AUDIT_BOXING_INTERVAL_MISMATCH]: 'Boks aralık süreleri bütçeyle eşleşmiyor.',
  [C.AUDIT_EXCESSIVE_CONSECUTIVE_ATTACK_COMBO]: 'Aynı kombinasyon çok ardışık tekrarlanmış.',
  [C.AUDIT_DEFENSE_UNAUTHORIZED]: 'Savunma bloku yetkisiz bir günde.',
  [C.AUDIT_DEFENSE_COUNT_MISMATCH]: 'Savunma blok sayısı beklenenle eşleşmiyor.',
  [C.AUDIT_DEFENSE_RULE_INVALID]: 'Geçersiz savunma kuralı kullanılmış.',
  [C.AUDIT_DEFENSE_CONTENT_MISMATCH]: 'Savunma içeriği kuralla uyuşmuyor.',
  [C.AUDIT_STRENGTH_TEMPLATE_INVALID]: 'Geçersiz kuvvet şablonu kullanılmış.',
  [C.AUDIT_STRENGTH_EQUIPMENT_INVALID]: 'Şablon, seçilen ekipmanla uyumsuz.',
  [C.AUDIT_STRENGTH_MOVEMENT_CAP_EXCEEDED]: 'Hareket sayısı izin verilen sınırı aşıyor.',
  [C.AUDIT_STRENGTH_TEMPLATE_ORDER_MISMATCH]: 'Kuvvet hareket sırası değiştirilmiş.',
  [C.AUDIT_STRENGTH_CONSTITUTION_FAILED]: 'Kuvvet seansı teknik kuralları sağlamıyor.',
  [C.AUDIT_STRENGTH_SET_COUNT_INVALID]: 'Set sayısı izin verilen aralıkta değil.',
  [C.AUDIT_STRENGTH_REP_INVALID]: 'Tekrar sayısı izin verilen aralıkta değil.',
  [C.AUDIT_STRENGTH_HOLD_INVALID]: 'Tutma süresi izin verilen aralıkta değil.',
  [C.AUDIT_UNILATERAL_SEMANTICS_INVALID]: 'Tek taraflı hareket semantiği hatalı.',
  [C.AUDIT_STRENGTH_WORK_BUDGET_MISMATCH]: 'Kuvvet çalışma süresi bütçeyi aşıyor.',
  [C.AUDIT_STRENGTH_RECOVERY_BUDGET_MISMATCH]: 'Toplanma (dinlenme) bütçesi eşleşmiyor.',
  [C.AUDIT_STRENGTH_REST_TOO_SHORT]: 'Setler arası dinlenme çok kısa (en az 15 sn).',
  [C.AUDIT_STRENGTH_TRANSITION_BUDGET_MISMATCH]: 'Geçiş süresi bütçesi eşleşmiyor.',
  [C.AUDIT_STRENGTH_TOTAL_MISMATCH]: 'Kuvvet blok toplamı bütçeyle eşleşmiyor.',
  [C.AUDIT_FORBIDDEN_LOAD_PRESCRIPTION]: 'Yasaklı yük (kg) reçetesi bulundu.',
  [C.AUDIT_FULL_PATTERN_COVERAGE_MISSED]: 'Ulaşılabilir olmasına rağmen hareket örüntüsü eksik.',
  [C.AUDIT_ROLLING_PATTERN_COVERAGE_MISSED]: '4 seanslık pencerede örüntü kapsamı eksik.',
  [C.AUDIT_PROGRAM_CHANGED_DURING_AUDIT]: 'Program kontrol sırasında değişti.',
  [C.AUDIT_MUTATED_BLUEPRINT]: 'Kontrol, program içeriğini değiştirdi (motor hatası).',
  [C.AUDIT_ENGINE_ERROR]: 'Kontrol motoru çalıştırılamadı.',
  [W.AUDIT_ADJACENT_STRENGTH_DAYS_UNAVOIDABLE]: 'Kuvvet günleri yan yana geldi (kaçınılmaz).',
  [W.AUDIT_HIGH_CONSECUTIVE_TRAINING_DENSITY]: 'Üst üste antrenman günü yoğunluğu yüksek.',
  [W.AUDIT_NO_UNSCHEDULED_WEEKDAY_GAP]: 'Haftanın her günü antrenman (boş gün yok).',
  [W.AUDIT_FIRST_ATTACK_ROUND_COMPLEX]: 'İlk saldırı rondası gereksiz karmaşık.',
  [W.AUDIT_DEFENSE_DISTRIBUTION_IMBALANCED]: 'Savunma kuralları dağılımı dengesiz.',
  [W.AUDIT_FULL_PATTERN_COVERAGE_LIMITED]: 'Tüm örüntü kapsamı sınırlarla ulaşılamaz.',
  [W.AUDIT_ROLLING_PATTERN_COVERAGE_LIMITED]: '4 seanslık pencerede tüm örüntüler ulaşılamaz.',
  [W.AUDIT_EXCESSIVE_TEMPLATE_REPEAT]: 'Aynı kuvvet şablonu çok ardışık tekrarlanmış.',
  [W.AUDIT_EXCESSIVE_ROW_VARIANT_REPEAT]: 'Aynı row varyantı çok ardışık tekrarlanmış.',
  [W.AUDIT_EXCESSIVE_SESSION_REPETITION]: 'Ardışık seanslar birbirinin birebir kopyası.',
  [W.AUDIT_BEGINNER_COMBINED_LOWER_DENSITY]: 'Başlangıç seviyesi combined programda alt vücut yoğunluğu yüksek.',
});